import Head from 'next/head'
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed"
import RightSidebar from '../components/RightSidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='flex bg-gray-100'>
        {/* Lefte Sidebar */}
        <Sidebar />
        {/* Feed Sidebar(Create post and posts) */}
        <Feed />
        {/* Right Sidebar */}
        <RightSidebar />
      </main>

     
    </div>
  )
}
